"use client"

import { useState, useEffect } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { z } from "zod"
import { ArrowLeft, Save } from "lucide-react"
import { GlassButton, GlassCard, GlassCardHeader, GlassCardTitle, GlassInput } from "@/components/glass"
import Link from "next/link"
import { Suspense } from "react"

const schema = z.object({
  planId: z.string().uuid(),
  dueDate: z.string().min(1, "กรุณาเลือกวันที่"),
  notes: z.string().optional(),
})

type FormData = z.infer<typeof schema>

function NewScheduleForm() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const planId = searchParams.get("planId")
  const [error, setError] = useState<string | null>(null)
  const [plan, setPlan] = useState<{ id: string; name: string; machine: { name: string } } | null>(null)

  const { register, handleSubmit, formState: { errors, isSubmitting }, setValue } = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: { planId: planId ?? "" },
  })

  useEffect(() => {
    if (planId) {
      setValue("planId", planId)
      fetch(`/api/maintenance/plans/${planId}`)
        .then(r => r.json())
        .then(d => setPlan(d.data))
        .catch(() => setError("ไม่พบแผนซ่อมบำรุง"))
    }
  }, [planId, setValue])

  const onSubmit = async (data: FormData) => {
    setError(null)
    const res = await fetch("/api/schedules", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...data, isAutoGenerated: false }),
    })
    if (!res.ok) {
      const json = await res.json()
      setError(json.error?.message ?? "เกิดข้อผิดพลาด")
      return
    }
    router.push("/maintenance/schedules")
    router.refresh()
  }

  return (
    <div className="space-y-6 max-w-xl">
      <div className="flex items-center gap-3">
        <Link href="/maintenance/schedules" className="p-2 hover:bg-muted rounded-lg text-muted-foreground">
          <ArrowLeft className="w-4 h-4" />
        </Link>
        <div>
          <h1 className="text-2xl font-bold text-foreground">สร้างกำหนดการใหม่</h1>
          <p className="text-muted-foreground text-sm mt-0.5">สร้างกำหนดการซ่อมบำรุงด้วยตนเอง</p>
        </div>
      </div>

      {error && (
        <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">{error}</div>
      )}

      {plan && (
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <p className="text-sm text-blue-800 font-medium">แผน: {plan.name}</p>
          <p className="text-xs text-blue-600 mt-0.5">เครื่องจักร: {plan.machine.name}</p>
        </div>
      )}

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
        <GlassCard>
          <GlassCardHeader><GlassCardTitle>ข้อมูลกำหนดการ</GlassCardTitle></GlassCardHeader>
          <div className="space-y-4">
            <GlassInput
              label="วันที่กำหนด"
              type="date"
              required
              error={errors.dueDate?.message}
              {...register("dueDate")}
            />
            <div>
              <label className="block text-sm font-medium text-foreground mb-1.5">หมายเหตุ</label>
              <textarea
                rows={3}
                placeholder="หมายเหตุเพิ่มเติม..."
                className="w-full px-3 py-2 border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                {...register("notes")}
              />
            </div>
          </div>
        </GlassCard>

        <div className="flex justify-end gap-3">
          <Link href="/maintenance/schedules" className="px-4 py-2 border border-border text-muted-foreground text-sm font-medium rounded-lg hover:bg-muted/60">
            ยกเลิก
          </Link>
          <GlassButton type="submit" loading={isSubmitting}>
            <Save className="w-4 h-4" />
            สร้างกำหนดการ
          </GlassButton>
        </div>
      </form>
    </div>
  )
}

export default function NewSchedulePage() {
  return (
    <Suspense fallback={<div className="flex items-center justify-center py-24"><div className="w-8 h-8 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" /></div>}>
      <NewScheduleForm />
    </Suspense>
  )
}
