import type { PrismaClient } from "@prisma/client"
import { z } from "zod"
import { calculateNextDueDate } from "@/lib/utils"

export const createMaintenanceScheduleSchema = z.object({
  planId: z.string().uuid(),
  dueDate: z.string(),
  isAutoGenerated: z.boolean().optional(),
})

export type CreateMaintenanceScheduleInput = z.infer<typeof createMaintenanceScheduleSchema>

export async function listMaintenanceSchedules(
  db: PrismaClient,
  params: {
    companyId: string
    branchId?: string | null
    status?: string | null
    machineId?: string | null
    dateFrom?: string | null
    dateTo?: string | null
    page: number
    pageSize: number
  }
) {
  const where = {
    machine: {
      branch: {
        companyId: params.companyId,
        ...(params.branchId && { id: params.branchId }),
      },
    },
    ...(params.machineId && { machineId: params.machineId }),
    ...(params.status && { status: params.status as never }),
    ...(params.dateFrom || params.dateTo
      ? {
          dueDate: {
            ...(params.dateFrom && { gte: new Date(params.dateFrom) }),
            ...(params.dateTo && { lte: new Date(params.dateTo) }),
          },
        }
      : {}),
  }

  const [data, total] = await Promise.all([
    db.maintenanceSchedule.findMany({
      where,
      include: {
        plan: {
          include: {
            type: { select: { id: true, name: true, code: true, color: true } },
          },
        },
        machine: {
          select: {
            id: true,
            name: true,
            code: true,
            branch: { select: { id: true, name: true } },
          },
        },
      },
      orderBy: { dueDate: "asc" },
      skip: (params.page - 1) * params.pageSize,
      take: params.pageSize,
    }),
    db.maintenanceSchedule.count({ where }),
  ])

  return {
    data,
    total,
    page: params.page,
    pageSize: params.pageSize,
    totalPages: Math.ceil(total / params.pageSize),
  }
}

export async function createMaintenanceSchedule(
  db: PrismaClient,
  params: { companyId: string; input: CreateMaintenanceScheduleInput }
) {
  const plan = await db.maintenancePlan.findFirst({
    where: {
      id: params.input.planId,
      machine: { branch: { companyId: params.companyId } },
    },
    select: { machineId: true },
  })

  if (!plan) {
    return { error: "Maintenance plan not found" as const, status: 404 as const }
  }

  const schedule = await db.maintenanceSchedule.create({
    data: {
      planId: params.input.planId,
      machineId: plan.machineId,
      dueDate: new Date(params.input.dueDate),
      isAutoGenerated: params.input.isAutoGenerated ?? false,
    },
  })

  return { data: schedule }
}

export async function deleteMaintenanceSchedule(
  db: PrismaClient,
  params: { id: string; companyId: string; userId: string; ipAddress?: string | null; userAgent?: string | null }
) {
  const schedule = await db.maintenanceSchedule.findFirst({
    where: { id: params.id, machine: { branch: { companyId: params.companyId } } },
    include: { workOrders: { select: { id: true } } },
  })

  if (!schedule) {
    return { error: "Not found" as const, status: 404 as const }
  }

  if (schedule.workOrders.length > 0) {
    return {
      error: "Cannot delete schedule because it already has work orders",
      status: 400 as const,
    }
  }

  await db.$transaction([
    db.maintenanceSchedule.delete({ where: { id: params.id } }),
    db.auditLog.create({
      data: {
        userId: params.userId,
        tableName: "maintenance_schedules",
        recordId: params.id,
        action: "delete",
        oldValues: JSON.parse(JSON.stringify(schedule)),
        ipAddress: params.ipAddress ?? null,
        userAgent: params.userAgent ?? null,
      },
    }),
  ])

  return { success: true }
}

export async function generateMaintenanceSchedules(db: PrismaClient, params: { today?: Date } = {}) {
  const today = params.today ?? new Date()
  let generated = 0

  const activePlans = await db.maintenancePlan.findMany({
    where: {
      isActive: true,
      frequencyUnit: { not: "runtime_hour" },
      OR: [{ endDate: null }, { endDate: { gte: today } }],
    },
  })

  for (const plan of activePlans) {
    const leadTimeCutoff = new Date(today)
    leadTimeCutoff.setDate(leadTimeCutoff.getDate() + plan.leadTimeDays)

    const lastGenerated = plan.lastGeneratedDate ?? plan.startDate
    let nextDue = calculateNextDueDate(lastGenerated, plan.frequencyUnit, plan.frequencyValue)

    while (nextDue <= leadTimeCutoff) {
      const exists = await db.maintenanceSchedule.findFirst({
        where: { planId: plan.id, dueDate: nextDue },
      })

      if (!exists) {
        await db.maintenanceSchedule.create({
          data: {
            planId: plan.id,
            machineId: plan.machineId,
            dueDate: nextDue,
            status: "pending",
            isAutoGenerated: true,
          },
        })
        generated++
      }

      await db.maintenancePlan.update({
        where: { id: plan.id },
        data: { lastGeneratedDate: nextDue },
      })

      nextDue = calculateNextDueDate(nextDue, plan.frequencyUnit, plan.frequencyValue)
    }
  }

  await db.maintenanceSchedule.updateMany({
    where: { dueDate: { lt: today }, status: "pending" },
    data: { status: "overdue" },
  })

  return { success: true, generated }
}
