import type { PrismaClient } from "@prisma/client"
import { z } from "zod"
import { calculateNextDueDate } from "@/lib/utils"

export const createMaintenancePlanSchema = z.object({
  machineId: z.string().uuid(),
  typeId: z.string().uuid(),
  name: z.string().min(1).max(255),
  description: z.string().optional(),
  frequencyUnit: z.enum(["day", "week", "month", "quarter", "year", "runtime_hour"]),
  frequencyValue: z.coerce.number().int().min(1),
  estimatedDurationMin: z.coerce.number().int().min(1).optional(),
  startDate: z.string(),
  endDate: z.string().optional(),
  leadTimeDays: z.coerce.number().int().min(0).default(7),
})

export const updateMaintenancePlanSchema = z.object({
  machineId: z.string().uuid().optional(),
  typeId: z.string().uuid().optional(),
  name: z.string().min(1).max(255).optional(),
  description: z.string().optional(),
  frequencyUnit: z.enum(["day", "week", "month", "quarter", "year", "runtime_hour"]).optional(),
  frequencyValue: z.coerce.number().int().min(1).optional(),
  estimatedDurationMin: z.coerce.number().int().min(1).optional(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  leadTimeDays: z.coerce.number().int().min(0).optional(),
  isActive: z.boolean().optional(),
})

export type CreateMaintenancePlanInput = z.infer<typeof createMaintenancePlanSchema>
export type UpdateMaintenancePlanInput = z.infer<typeof updateMaintenancePlanSchema>

export async function listMaintenancePlans(
  db: PrismaClient,
  params: { companyId: string; machineId?: string | null; isActive?: string | null }
) {
  return db.maintenancePlan.findMany({
    where: {
      machine: { branch: { companyId: params.companyId } },
      ...(params.machineId && { machineId: params.machineId }),
      ...(params.isActive !== null && params.isActive !== undefined && { isActive: params.isActive === "true" }),
    },
    include: {
      machine: { select: { id: true, name: true, code: true, branch: { select: { name: true } } } },
      type: { select: { id: true, name: true, code: true, color: true } },
      _count: { select: { schedules: true } },
    },
    orderBy: { createdAt: "desc" },
  })
}

export async function createMaintenancePlan(
  db: PrismaClient,
  params: { userId: string; input: CreateMaintenancePlanInput }
) {
  const { startDate, endDate, ...rest } = params.input

  const plan = await db.maintenancePlan.create({
    data: {
      ...rest,
      startDate: new Date(startDate),
      endDate: endDate ? new Date(endDate) : null,
      isActive: true,
      createdBy: params.userId,
    },
  })

  const firstDue = calculateNextDueDate(new Date(startDate), rest.frequencyUnit, rest.frequencyValue)
  await db.maintenanceSchedule.create({
    data: {
      planId: plan.id,
      machineId: plan.machineId,
      dueDate: firstDue,
      status: "pending",
      isAutoGenerated: true,
    },
  })
  await db.maintenancePlan.update({ where: { id: plan.id }, data: { lastGeneratedDate: firstDue } })

  return plan
}

export async function getMaintenancePlanById(
  db: PrismaClient,
  params: { id: string; companyId: string }
) {
  return db.maintenancePlan.findFirst({
    where: { id: params.id, machine: { branch: { companyId: params.companyId } } },
    include: {
      machine: { select: { id: true, name: true, code: true } },
      type: { select: { id: true, name: true, code: true, color: true } },
    },
  })
}

export async function updateMaintenancePlan(
  db: PrismaClient,
  params: { id: string; companyId: string; input: UpdateMaintenancePlanInput }
) {
  const plan = await db.maintenancePlan.findFirst({
    where: { id: params.id, machine: { branch: { companyId: params.companyId } } },
  })
  if (!plan) return null

  const { startDate, endDate, description, estimatedDurationMin, ...rest } = params.input
  return db.maintenancePlan.update({
    where: { id: params.id },
    data: {
      ...rest,
      description: description === "" ? null : description,
      estimatedDurationMin: Number.isNaN(estimatedDurationMin) ? null : estimatedDurationMin,
      startDate: startDate ? new Date(startDate) : undefined,
      endDate: endDate ? new Date(endDate) : endDate === "" ? null : undefined,
    },
  })
}

export async function deactivateMaintenancePlan(
  db: PrismaClient,
  params: { id: string; companyId: string; userId: string; ipAddress?: string | null; userAgent?: string | null }
) {
  const plan = await db.maintenancePlan.findFirst({
    where: { id: params.id, machine: { branch: { companyId: params.companyId } } },
  })
  if (!plan) return null

  await db.$transaction([
    db.maintenancePlan.update({ where: { id: params.id }, data: { isActive: false } }),
    db.auditLog.create({
      data: {
        userId: params.userId,
        tableName: "maintenance_plans",
        recordId: params.id,
        action: "delete",
        oldValues: JSON.parse(JSON.stringify(plan)),
        newValues: JSON.parse(JSON.stringify({ ...plan, isActive: false })),
        ipAddress: params.ipAddress ?? null,
        userAgent: params.userAgent ?? null,
      },
    }),
  ])

  return { success: true }
}
