export {
  ASSET_TYPES,
  ASSET_STATUSES,
  ASSET_OWNERSHIPS,
  createAssetSchema,
  updateAssetSchema,
  createAsset,
  updateAsset,
  deleteAsset,
  listAssets,
  getAsset,
  suggestNextAssetCode,
  listAccessibleBranches,
  listActiveSuppliers,
  getAssetFormOptions,
  assetCodePrefix,
  formatAssetCode,
  parseAssetCodeSeq,
  type CreateAssetInput,
  type UpdateAssetInput,
  type AssetDto,
} from "./application/asset-service"
